# Generated by Django 5.1 on 2024-08-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevists',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
